# Generated by Django 4.0.4 on 2022-04-21 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('adverts', '0004_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_adverts', through='adverts.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
